server:
  port: ${SERVER_PORT:8081}

spring:
  ai:
    mcp:
      server:
        enabled: true
        name: yougile-mcp-server
        version: 1.0.0
        protocol: STREAMABLE

yougile:
  api:
    key: ${YOUGILE_API_KEY:hX-SLTywqax7lTDimL4dvvKepwhQNUIRzmHXfz-EoO4Ar7wPgqnlR-tEoP1xVuiB}
    base-url: ${YOUGILE_API_BASE_URL:https://yougile.com/api-v2}
