server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.ai.model.ollama.autoconfigure.OllamaApiAutoConfiguration
  ai:
    model:
      embedding: ollama
      chat: ollama
    ollama:
      chat:
        options:
          model: qwen3.5:2b
      base-url: http://localhost:11434
      embedding:
        enabled: true
        options:
          model: qwen3-embedding:8b
    mcp:
      client:
        enabled: true
        name: yougile-alert-client
        version: 1.0.0
        type: ASYNC
        streamable-http:
          connections:
            yougile-mcp:
              url: ${MCP_SERVER_URL:http://localhost:8081}
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/alertbot}
    username: ${SPRING_DATASOURCE_USERNAME:alertbot}
    password: ${SPRING_DATASOURCE_PASSWORD:alertbot_pass}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:8684989309:AAFKbXiM_81o9a-GaGpCOYDt2msxKSO_RWk}
    proxy:
      host: ${TELEGRAM_PROXY_HOST:127.0.0.1}
      port: ${TELEGRAM_PROXY_PORT:1080}
      type: ${TELEGRAM_PROXY_TYPE:SOCKS}

yougile:
  api:
    key: ${YOUGILE_API_KEY:jeffSEZnASdXC-kawbSJFE0nrZ5Y0Bobn+5jelGUr77vVnGNy-S6vmSpKYQ9yNK7"}
    base-url: ${YOUGILE_API_BASE_URL:https://yougile.com/api-v2}
  default:
    column-id: ${YOUGILE_DEFAULT_COLUMN_ID:backlog}
