server:
  port: ${SERVER_PORT:8080}

spring:
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      embedding:
        enabled: true # Включить автоконфигурацию для эмбеддингов (включено по умолчанию)[reference:13]
        options:
          model: qwen3-embedding:8b # Имя загруженной модели[reference:14][reference:15]
    mcp:
      client:
        enabled: true
        name: yougile-alert-client
        version: 1.0.0
        type: SYNC
        streamable-http:
          connections:
            yougile-mcp:
              url: ${MCP_SERVER_URL:http://localhost:8081}
    openai:
      api-key: ${OPENCODE_API_KEY:e0965efdf6c24e2899280d82ea51fd23.TB5HCDh1ff-uG43U0TwDivaZ}
      base-url: ${OLLAMA_BASE_URL:http://127.0.0.1:11434}
      chat:
        options:
          model: ${OPENCODE_MODEL:qwen3-embedding:8b}
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/alertbot}
    username: ${SPRING_DATASOURCE_USERNAME:alertbot}
    password: ${SPRING_DATASOURCE_PASSWORD:alertbot_pass}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    token: 8684989309:AAFKbXiM_81o9a-GaGpCOYDt2msxKSO_RWk

yougile:
  api:
    key: ${YOUGILE_API_KEY:hX-SLTywqax7lTDimL4dvvKepwhQNUIRzmHXfz-EoO4Ar7wPgqnlR-tEoP1xVuiB"}
    base-url: ${YOUGILE_API_BASE_URL:https://yougile.com/api-v2}
  default:
    column-id: ${YOUGILE_DEFAULT_COLUMN_ID}
